### PR TITLE
Ignore

### PR DESCRIPTION
**Pull request by dpastoor**
@HelenaEdlund want to give the ignore implementation a look through.

Basically, the idea is that you can specify a (vector) of strings that will be contained inside the ignore=() statement

as you can see from the tests in test-ignore-nonmem, this is the underlying class method

the top level api will be

```
bp %>%
   ignore("BQL.EQ.1")
```

or for multiple 

```
bp %>%
   ignore(c("BQL.EQ.1", "TIME>=5"))
```

by default if there are ignore statements (eg a base blueprint you're adding additional stuff later), but this can be overwritten by using `.overwrite = TRUE` 

Finally you can selectively drop a statement. 

```
new_bp <- bp %>%
   ignore(c("BQL.EQ.1", "TIME>=5"))

# later

new_bp %>% ignore(.drop = "TIME>=5")
# now only BQL.EQ.1 will be present
```

Any problems or requests with the api, either naming or feature-wise?

### CODE REVIEW

**Comment by HelenaEdlund** [comment]
@dpastoor I like this implementation. You could consider doing the same for accept? (and have some message on that they cannot be used together) 

Not only related to this but we had a little bit of discussion here today on the fact that you cannot remove things once they are added. This might actually be a good thing so I am not sure if we should bother with the .drop part. In one way it would be very convenient but at the same time you cannot/becomes more difficult to track the parent model. Just food for thought since we were talking about creating some functionality that would pick up the line/tree of model development.

**Comment by HelenaEdlund** [comment]
Second though, should this be an argument of the with_data() instead of a separate function?

**Comment by dpastoor** [comment]
@HelenaEdlund not with_data() as you may want different models with different levels of ignore, especially if you wanted to do different types of estimation designs for something akin to optimal design.

regarding `.drop` I'm on the fence with that as well, I see what you mean by making it harder to track lineage. I think what I'll do is make it easy to query the existing ignores so if people want to modify the total vector, they can themselves, but then make ignore() only additive/overwriting

**Comment by dpastoor** [comment]
Can you remind me, I'm being lazy about looking in the nonmem docs - nonmem can only take either accept _or_ ignore in a single control stream?

I can constrain that as needed.

**Comment by HelenaEdlund** [comment]
Yes, that is my understanding. If multiple ignore/accept statements are added in one script accept work as an 'or' logical and the ignore as 'and' (and cannot be combined with each other).

**Pull request merged**
